export const primaries = [
  "AR-23 Liberator",
  "AR-23P Liberator Penetrator",
  "AR-23C Liberator Concussive",
  "AR-61 Tenderizer",
  "BR-14 Adjudicator",
  "R-63 Diligence",
  "R-63CS Diligence Counter Sniper",
  "MP-98 Knight",
  "SMG-37 Defender",
  "SMG-72 Pummeler",
  "SG-8 Punisher",
  "SG-8S Slugger",
  "SG-225 Breaker",
  "SG-225SP Breaker Spray&Pray",
  "SG-225IE Breaker Incendiary",
  "CB-9 Exploding Crossbow",
  "JAR-5 Dominator",
  "R-36 Eruptor",
  "SG-8P Punisher Plasma",
  "ARC-12 Blitzer",
  "LAS-5 Scythe",
  "LAS-16 Sickle",
  "PLAS-1 Scorcher",
  "PLAS-101 Purifier",
];

export const secondaries = [
  "P-2 Peacemaker",
  "P-16 Redeemer",
  "GP-31 Grenade Pistol",
  "LAS-7 Dagger",
  "P-113 Verdict",
  "P-4 Senator",
];

export const grenades = [
  "G-6 Frag",
  "G-12 High Explosive",
  "G-10 Incendiary",
  "G-16 Impact",
  "G-13 Incendiary Impact",
  "G-23 Stun",
  "G-3 Smoke",
  "G-123 Thermite",
];

export const armors = [
  "FS-37 Ravager",
  "CW-4 Arctic Ranger",
  "CE-74 Breaker",
  "CE-67 Titan",
  "CM-21 Trench Paramedic",
  "CE-07 Demolition Specialist",
  "FS-38 Eradicator",
  "EX-00 Prototype X",
  "SC-37 Legionnaire",
  "B-08 Light Gunner",
  "SC-30 Trailblazer Scout",
  "SC-34 Infiltrator",
  "SA-25 Steel Trooper",
  "SA-12 Servo Assisted",
  "CE-35 Trench Engineer",
  "CE-27 Ground Breaker",
  "CM-09 Bonesnapper",
  "CM-10 Clinician",
  "SC-15 Drone Master",
  "EX-03 Prototype 3",
  "EX-16 Prototype 16",
  "FS-34 Exterminator",
  "DP-40 Hero of the Federation",
  "TR-9 Cavalier of Democracy",
  "DP-11 Champion of the People",
  "CM-14 Physician",
  "TR-117 Alpha Commander",
  "CE-81 Juggernaut",
  "DP-53 Savior of the Free",
  "B-24 Enforcer",
  "TR-7 Ambassador of the Brand",
  "B-01 Tactical",
  "CW-9 White Wolf",
  "SA-04 Combat Technician",
  "FS-55 Devastator",
  "CW-22 Kodiak",
  "SA-32 Dynamo",
  "CM-17 Butcher",
  "FS-61 Dreadnought",
  "B-27 Fortified Commando",
  "FS-05 Marksman",
  "FS-11 Executioner",
  "CE-64 Grenadier",
  "FS-23 Battle Master",
  "TR-62 Knight",
  "CW-36 Winter Warrior",
];

export const boosters = [
  "Vitality Enhancement",
  "Stamina Enhancement",
  "Muscle Enhancement",
  "UAV Recon Booster",
  "Increased Reinforcement Budget",
  "Flexible Reinforcement Budget",
  "Hellpod Space Optimization",
  "Localization Confusion",
  "Expert Extraction Pilot",
  "Motivational Shocks",
];

export const stratagems = [
  { name: "Machine Gun", backpack: false, supportWeapon: true },
  { name: "Anti-Material Rifle", backpack: false, supportWeapon: true },
  { name: "Stalwart", backpack: false, supportWeapon: true },
  { name: "Expendable Anti-Tank", backpack: false, supportWeapon: true },
  { name: "Recoilless Rifle", backpack: true, supportWeapon: true },
  { name: "Flamethrower", backpack: false, supportWeapon: true },
  { name: "Autocannon", backpack: true, supportWeapon: true },
  { name: "Heavy Machine Gun", backpack: false, supportWeapon: true },
  { name: "Airburst Rocket Launcher", backpack: true, supportWeapon: true },
  { name: "Railgun", backpack: false, supportWeapon: true },
  { name: "Spear", backpack: true, supportWeapon: true },
  { name: "Orbital Gatling Barrage", backpack: false, supportWeapon: false },
  { name: "Orbital Airburst Strike", backpack: false, supportWeapon: false },
  { name: "Orbital 120MM HE Barrage", backpack: false, supportWeapon: false },
  { name: "Orbital 380MM HE Barrage", backpack: false, supportWeapon: false },
  { name: "Orbital Walking Barrage", backpack: false, supportWeapon: false },
  { name: "Orbital Laser", backpack: false, supportWeapon: false },
  { name: "Orbital Railcannon Strike", backpack: false, supportWeapon: false },
  { name: "Eagle Strafing Run", backpack: false, supportWeapon: false },
  { name: "Eagle Airstrike", backpack: false, supportWeapon: false },
  { name: "Eagle Cluster Bomb", backpack: false, supportWeapon: false },
  { name: "Eagle Napalm Airstrike", backpack: false, supportWeapon: false },
  { name: "Jump Pack", backpack: true, supportWeapon: false },
  { name: "Eagle Smoke Strike", backpack: false, supportWeapon: false },
  { name: "Eagle 110MM Rocket Pods", backpack: false, supportWeapon: false },
  { name: "Eagle 500KG Bomb", backpack: false, supportWeapon: false },
  { name: "Orbital Precision Strike", backpack: false, supportWeapon: false },
  { name: "Orbital Gas Strike", backpack: false, supportWeapon: false },
  { name: "Orbital EMS Strike", backpack: false, supportWeapon: false },
  { name: "Orbital Smoke Strike", backpack: false, supportWeapon: false },
  { name: "HMG Emplacement", backpack: false, supportWeapon: false },
  { name: "Shield Generator Relay", backpack: false, supportWeapon: false },
  { name: "Tesla Tower", backpack: false, supportWeapon: false },
  { name: "Anti-Personnel Minefield", backpack: false, supportWeapon: false },
  { name: "Supply Pack", backpack: true, supportWeapon: false },
  { name: "Grenade Launcher", backpack: false, supportWeapon: true },
  { name: "Laser Cannon", backpack: false, supportWeapon: true },
  { name: "Incendiary Mines", backpack: false, supportWeapon: false },
  { name: `"Guard Dog" Rover`, backpack: false, supportWeapon: true },
  { name: "Ballistic Shield Backpack", backpack: false, supportWeapon: true },
  { name: "Arc Thrower", backpack: false, supportWeapon: true },
  { name: "Quasar Cannon", backpack: false, supportWeapon: true },
  { name: "Shield Generator Pack", backpack: false, supportWeapon: true },
  { name: "Machine Gun Sentry", backpack: false, supportWeapon: false },
  { name: "Gatling Sentry", backpack: false, supportWeapon: false },
  { name: "Mortar Sentry", backpack: false, supportWeapon: false },
  { name: `"Guard Dog"`, backpack: false, supportWeapon: true },
  { name: "Autocannon Sentry", backpack: false, supportWeapon: false },
  { name: "Rocket Sentry", backpack: false, supportWeapon: false },
  { name: "EMS Mortar Sentry", backpack: false, supportWeapon: false },
  { name: "Patriot Exosuit", backpack: false, supportWeapon: false },
];
